### ISSUE TITLE
Mean key -> most common key

### ISSUE THREAD

**Issue by SharkyFlou** [HugoLAMOUREUX/Spotidata#62]
### Summary

In the Playlists details, there is the "Mean key" but it doesn't make any sense to get an average out of the key.

What would be more logical is to have the most common key, so like the genres or the artists, get the number of each key, and then return only the most common one.

### Basic Example

Mean key : 5.13
Could be now Most common key : F
More information here : https://developer.spotify.com/documentation/web-api/reference/get-several-audio-features
And here : https://en.wikipedia.org/wiki/Pitch_class

### Drawbacks

Allow to really know the most used key in the playlists.

**Comment by Anurag-Raut** [comment]
I'll like to work on this.

but I am stuck on loading and not able to get details from spotify API

![image](https://github.com/HugoLAMOUREUX/Spotidata/assets/102049482/7afca3ed-64ef-478f-857a-4b2a772ea7b0)

I have sent the mail to hugo.lamoureux18@gmail.com regarding authorization

**Comment by HugoLAMOUREUX** [comment]
Thanks for you will to contribute to our project ! Eveything should be fine since you are authorized now

**Comment by Anurag-Raut** [comment]
Should I replace Mean key card with Most common Key
something like this?
![image](https://github.com/HugoLAMOUREUX/Spotidata/assets/102049482/25558648-31a5-4ac4-8f8b-97c50be1ecf1)
or add a new card instead?

Also to get most common key I'm storing the keys from each track in an array (since the keys would be in range -1 to 11 ) and then finding index of maximum value in that array 

like this
` return_value.keys=mapKeyToPitch(return_value.key_array.indexOf(Math.max(...return_value.key_array)));`


In case of 2 or more keys with same number of occurrences in playlist should show only one key or all the keys with max occurrence?

**Comment by Anurag-Raut** [comment]
Please review PR #64 and let me know if any changes need to be done
